-- Create new table spliting winner and loser of single match into two new rows

CREATE TABLE player_matches AS
SELECT  winner_id AS player_id, 
        winner_seed AS player_seed, 
        winner_name AS player_name, 
        winner_hand AS player_hand, 
        winner_ht AS player_height,
        winner_ioc AS player_ioc,
        winner_age AS player_age,
        winner_rank AS ranking,
        loser_id AS opponent_id,
        loser_name AS opponent_name,
        score,
        1 AS won_match,
        tourney_id, 
		tourney_name, 
        year,
		surface, 
        draw_size, 
        tourney_date, 
        w_ace AS aces,
        w_df AS df,
        w_svpt AS serve_points,
        w_1stIn AS first_serves_in,
        w_1stWon AS first_serve_points_won,
        w_2ndWon AS second_serve_points_won,
        w_SvGms AS service_games,
        l_SvGms AS return_games,
        w_bpSaved AS break_points_saved,
        w_bpFaced AS break_points_faced,
        l_bpFaced AS break_points_generated,
        l_bpFaced - l_bpSaved AS break_points_won
        
         
FROM raw_matches
UNION ALL
SELECT  loser_id AS player_id, 
        loser_seed AS player_seed, 
        loser_name AS player_name, 
        loser_hand AS player_hand, 
        loser_ht AS player_height,
        loser_ioc AS player_ioc,
        loser_age AS player_age,
        loser_rank AS ranking,
        winner_id AS opponent_id,
        winner_name AS opponent_name,
        score,
        0 AS won_match,
        tourney_id, 
		tourney_name, 
        year,
		surface, 
        draw_size, 
        tourney_date, 
        l_ace AS aces,
        l_df AS df,
        l_svpt AS serve_points,
        l_1stIn AS first_serves_in,
        l_1stWon AS first_serve_points_won,
        l_2ndWon AS second_serve_points_won,
        l_SvGms AS service_games,
        w_SvGms AS return_games,
        l_bpSaved AS break_points_saved,
        l_bpFaced AS break_points_faced,
        w_bpFaced AS break_points_generated,
        w_bpFaced - w_bpSaved AS break_points_won
FROM raw_matches
        